using BinaryKits.Zpl.Viewer;
using BinaryKits.Zpl.Viewer.ElementDrawers;
using SkiaSharp;
using ZplViewer.Core;

if (args.Length != 2) throw new ArgumentException("Usage: RenderComparison <label.zpl> <output-directory>");
var source = File.ReadAllText(args[0]);
var output = Path.GetFullPath(args[1]);
Directory.CreateDirectory(output);
var settings = RenderSettings.Shipping4By8;
var storage = new PrinterStorage();
var labels = new ZplAnalyzer(storage).Analyze(source).LabelInfos;
var oldRenderer = new ZplElementDrawer(storage, new DrawerOptions { OpaqueBackground = true });
var beforeBytes = oldRenderer.Draw(labels.Single().ZplElements, settings.WidthMm, settings.HeightMm, settings.DotsPerMm);
var afterBytes = new ZplRenderer().Render(source, settings).Pages.Single();
using var before = SKBitmap.Decode(beforeBytes);
using var after = SKBitmap.Decode(afterBytes);
using var canvasBitmap = new SKBitmap(before.Width * 2 + 30, before.Height + 50);
using var canvas = new SKCanvas(canvasBitmap);
canvas.Clear(SKColors.White);
canvas.DrawBitmap(before, 0, 50);
canvas.DrawBitmap(after, before.Width + 30, 50);
using var headingFont = new SKFont(SKTypeface.Default, 24);
using var paint = new SKPaint { Color = SKColors.Black, IsAntialias = true };
canvas.DrawText("Antes: BinaryKits predeterminado", 12, 32, headingFont, paint);
canvas.DrawText("Después: fuente local incluida", before.Width + 42, 32, headingFont, paint);
using var image = SKImage.FromBitmap(canvasBitmap);
using var png = image.Encode(SKEncodedImageFormat.Png, 100);
File.WriteAllBytes(Path.Combine(output, "comparison.png"), png.ToArray());
File.WriteAllBytes(Path.Combine(output, "before.png"), beforeBytes);
// Flatten transparency only in the exported comparison, not in the renderer.
using var page = new SKBitmap(after.Width, after.Height);
using var pageCanvas = new SKCanvas(page);
pageCanvas.Clear(SKColors.White);
pageCanvas.DrawBitmap(after, 0, 0);
using var pageImage = SKImage.FromBitmap(page);
using var pagePng = pageImage.Encode(SKEncodedImageFormat.Png, 100);
File.WriteAllBytes(Path.Combine(output, "after.png"), pagePng.ToArray());
Console.WriteLine($"{after.Width} × {after.Height} px; {output}");
